apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: jruedas-az-secret-store
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      vaultUrl: https://jruedas-tfm-vault.vault.azure.net