apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    path: charts/cert-manager
    repoURL: https://github.com/JRuedas/tfm-argocd-apps.git
    targetRevision: HEAD
    helm:
      parameters:
        - name: subscriptionID
          value: "${subscriptionID}"
        - name: clientID
          value: "${clientID}"                              
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true