argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  redis:
    enabled: false
  applicationSet:
    enabled: false
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      hosts:
        - argocd.jruedas.dev
      https: true
      tls:
        - secretName: argocd-tls
          hosts:
            - argocd.jruedas.dev