argo-cd:
  server:
    extraArgs:
      - --insecure
    config:
      configManagementPlugins: |-
        - name: argocd-vault-plugin
          generate:
            command: ["argocd-vault-plugin"]
            args: ["generate", "./"]
  repoServer:
    volumes:
      - name: custom-tools
        emptyDir: {}
    envFrom:
    - secretRef:
        name: argocd-vault-plugin-credentials
    volumeMounts:
      - name: custom-tools
        mountPath: /usr/local/bin/argocd-vault-plugin
        subPath: argocd-vault-plugin
    initContainers:
      - name: download-vault-plugin
        image: alpine:3.8
        command: [sh, -c]
        args:
          - >-
            wget -O argocd-vault-plugin
            https://github.com/IBM/argocd-vault-plugin/releases/download/v1.1.1/argocd-vault-plugin_1.1.1_linux_amd64 &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/            
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools